### ISSUE TITLE
4. Scratch the public interface of your module

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/rss-feed-emitter#122]
This is, without any doubt, the **most important decision** you will make about your module :+1: 

The public interface will define not only the user experience of your module, but keep in mind people will bind their systems to your module and they will **depend** on the methods and behavior you will define here.

If you decide to change this in future versions, you will insert what we call a **breaking change**. It's completely normal to do this, but it comes with a cost to everyone involved.

### The overview

What we want the use be able to do with this module is basically:

 * Create an instance of the module
 * Add new feed urls to that instance
 * Be able to control the refresh rate of every feed
 * List all feeds in the instance
 * Receive events for every new feed item found
 * Remove a feed from the instance
 * Destroy the instance and remove all registered feeds

So, the public interface will expose methods like:

 * Create instance
 * Add
 * Remove
 * List
 * Listen
 * Destroy

## Create instance
There's various ways to expose an instance for the developer to work with. My favorite one is Factory, but the most popular is an instance created from a Class <sup>[1]</sup> using the `new` keyword.

So, the very first action is to require the module (considering you're using Node.js) and then `new` it:

``` js
let RssFeedEmitter = require('rss-feed-emitter');
let feeder = new RssFeedEmitter();
```

*<sup>[1] JavaScript doesn't have the classical Class, but don't mind this now.</sup>*

### Add
Now let's imagine what's the user experience to add feeds to that instance. We can think in something like this:

``` js
feeder.add('http://www.nintendolife.com/feeds/latest');
```

This is the simplest way we can get, right? But if we want to control the refresh rate of that feed, the developer will need to pass in a `refresh` property and we will want something like this:

``` js
 feeder.add({
  url: 'http://www.nintendolife.com/feeds/latest',
  refresh: 1000
})
```

We can also assume a default value to the `refresh` property and it's nice to accept something like:

``` js
feeder.add({
  url: 'http://www.nintendolife.com/feeds/latest'
})
```

You may ask:

> *Well, if `refresh` is not required, why  we can't accept both `string` and `object` to be used in the `add` method?*

Glad you asked. I don't think it's a good practice to expose exact the same action in different ways since this can lead to unexpected bugs, will add more behaviors and paths to your code, you will have to coverage it with more tests and documentation. But in the and it's a tradeoff and it's your choice.

### Remove

Since we can add things to that module, would be very nice to remove them. I can't think of anything simpler than this:

``` js
feeder.remove('http://www.nintendolife.com/feeds/latest');
```

### List

A method to list all registered feeds would be very nice if, for example, we want to iterate over them to return to the end user.

``` js
feeder.list();
// -> this will out put an Array of feeds
```

### Listen

To listen for asynchronous events, we need to expose an Event Listener interface and for every new `item` emitted, the developer have to attach a callback function to handle it. Something like:

``` js
feeder.on('new-item', function(item) {
  console.log(item);
})
```

### Destroy

We can use a `destroy` method in mainly two situations: when a system is being shut down gracefully and, when we get to automated tests, clean everything after after every test. This method is simple as `list`, and the developer will only need do invoke it:

``` js
feeder.destroy();
```

### Conclusion

We didn't code anything yet, but what do you think of the interface we're exposing to the developer?

``` js
let RssFeedEmitter = require('rss-feed-emitter');
let feeder = new RssFeedEmitter();

feeder.add( {...} )
feeder.remove( 'url' );
feeder.list();
feeder.on( 'new-item', callback);
feeder.destroy();
```

It makes sense, right? Great :+1: 

### Next step

[5. Try to scratch an overview of the internals](https://github.com/filipedeschamps/rss-feed-emitter/issues/123)

**Comment by segmentationfaulter** [comment]
I think a typo here:

>  But in the and it's a tradeoff and it's your choice.

Probably you want to write 'in the end' rather than 'in the and'.
A super awesome tutorial by the way!

**Comment by filipedeschamps** [comment]
@segmentationfaulter perfect, fixed :+1:

**Comment by JimLynchCodes** [comment]
I don't understand what this means, "Scratch the public interface of your module"?

Is this phrase translated from another language?

**Comment by TobiTenno** [comment]
this is, like, very very old.... this was a tutorial for setting up initial libraries
