### ISSUE TITLE
10. Create your first automated test to cover the public interface

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/rss-feed-emitter#128]
Now things starts to become exciting. Understand how to do automated tests is a must if you want to consider yourself a good developer.

### Assertion library

We are going to use Mocha as our test runner, but first we need an **assertion library**. An assertion library is responsible to compare values, for example, expect that variable A has the value X, and if it doesn't, throw an error to mark that test as failed.

We will use [chai](https://www.npmjs.com/package/chai), which is one of the best in town:

```
$ npm install --save-dev chai
```

### Test runner

Like said before, we will use Mocha to run our tests scenarios:

```
$ npm install --save-dev mocha
```

### Unit tests

We are ready to write our first unit test. Our objective here is to ensure we are correctly creating an instance and it has all the public methods we coded before.

Create a file called `test/unit/rss-feed-emitter.spec.js`. Notice the `.spec.js` in it's name. This is a pattern and you will understand later what is used to.

So, let's start to import our own module to the test file:

``` js
'use strict';

import RssFeedEmitter from '../../src/rss-feed-emitter.js';
```

Now let's import Chai and use it's `expect` assertion function:

``` js
'use strict';

import RssFeedEmitter from '../../src/rss-feed-emitter.js';
import chai from 'chai';

let expect = chai.expect;
```

And we are ready to test the most basic thing: if we create and instance from our module, does it return and object as expected? Let's write a test for this scenario:

``` js
'use strict';

import RssFeedEmitter from '../../src/rss-feed-emitter.js';
import chai from 'chai';

let expect = chai.expect;

describe( 'RssFeedEmitter ( unit )', () => {

  describe( 'when instantiated', () => {

    let feeder = new RssFeedEmitter();

    it( 'should return an Object', () => {

      expect( feeder ).to.be.an( 'object' );

    } );

  } );

} );
```

So we expect that the instance `feeder` is an `object`. How can we run this spec to see the results?

### Running tests

Since we wrote the source code and test in ES6, we need to tell Mocha to use a compiler (Babel) and you do this by passing some arguments to it:

We are going to run this a lot of times so it's better to create a `npm script` to easy access this command.

Edit your `package.json` and add a new line in the `scripts` session:

``` js
{
  "name": "repository-demo-github",
  "version": "0.0.1",
  "description": "This is a demonstration repository",
  "main": "index.js",
  "scripts": {
    "test-unit": "mocha --compilers js:babel-core/register test/unit/**/*.spec.js"
  },
  //...
```

See what we did there? Now, everytime you run this in your command line:

```
$ npm run test-unit
```

Npm will run `mocha --compilers js:babel-core/register test/unit/**/*.spec.js`

Let me explain this command:

 * `mocha`<br> Binary that read and runs the tests.

 * `--compilers js:babel-core/register`<br> Register Babel as a compiler

* `test/unit/**/*.spec.js`<br> The pattern Mocha will search for files. See the `*.spec.js`? We can now add other files inside the test directory and if they don't match the pattern, won't be executed as test specs.

Now, run the `npm run test-unit` and you will see something like this:

![image](https://cloud.githubusercontent.com/assets/4248081/13381254/532d0a38-de36-11e5-8d3c-ebaf47f1c5f3.png)

Amazing! Let's write the rest of the assertions to ensure all public interfaces are there, for example, we expect that `add` method will be a function, right?

``` js
'use strict';

import RssFeedEmitter from '../../src/rss-feed-emitter.js';
import chai from 'chai';

let expect = chai.expect;

describe( 'RssFeedEmitter ( unit )', () => {

  describe( 'when instantiated', () => {

    let feeder = new RssFeedEmitter();

    it( 'should return an Object', () => {

      expect( feeder ).to.be.an( 'object' );

    } );

  } );

  describe( '#add', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.add ).to.be.a( 'function' );

    } );

  } );

} );
```

Results in:

![image](https://cloud.githubusercontent.com/assets/4248081/13381277/ebf97396-de36-11e5-9fbb-0acdeb7d94ba.png)

Let's add all public methods:

``` js
'use strict';

import RssFeedEmitter from '../../src/rss-feed-emitter.js';
import chai from 'chai';

let expect = chai.expect;

describe( 'RssFeedEmitter ( unit )', () => {

  describe( 'when instantiated', () => {

    let feeder = new RssFeedEmitter();

    it( 'should return an Object', () => {

      expect( feeder ).to.be.an( 'object' );

    } );

  } );

  describe( '#add', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.add ).to.be.a( 'function' );

    } );

  } );

  describe( '#emit', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.emit ).to.be.a( 'function' );

    } );

  } );

  describe( '#on', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.on ).to.be.a( 'function' );

    } );

  } );

  describe( '#list', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.list ).to.be.a( 'function' );

    } );

  } );

  describe( '#remove', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.remove ).to.be.a( 'function' );

    } );

  } );

  describe( '#destroy', () => {

    let feeder = new RssFeedEmitter();

    it( 'should be a Function', () => {

      expect( feeder.remove ).to.be.a( 'function' );

    } );

  } );

} );
```

Results in:

![image](https://cloud.githubusercontent.com/assets/4248081/13381310/99c140b2-de37-11e5-8fcd-090f58449863.png)

### Next step
[11. Configure Travis CI for automated tests](https://github.com/filipedeschamps/rss-feed-emitter/issues/129)

**Comment by caiocutrim** [comment]
coool
