### ISSUE TITLE
12. Configure Code Climate for code coverage

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/rss-feed-emitter#132]
You can't trust the results coming from another developer... you can't even trust the results coming from your computer :+1: you need to centralize all analysis in another specialized machine that the only thing it does is to ensure the quality and behavior of your code inside a clean environment.

## Create an account

First you need to create an account in https://codeclimate.com (it's free for open source projects).

## Add repository

After you finish your onboard, click in the **Add Open Source Repo** button:

![image](https://cloud.githubusercontent.com/assets/4248081/13512859/1c67d8cc-e17c-11e5-8ac6-b8ba661fb674.png)

Insert the location of the repository we created in the [Create a Github repository](https://github.com/filipedeschamps/rss-feed-emitter/issues/120) step and then click in the **Import Repo from Github**:

![image](https://cloud.githubusercontent.com/assets/4248081/13512921/5864b1ce-e17c-11e5-841e-fbb0c2b7b069.png)

## Configuration

It will analyze your repository and then warn that you're using a default configuration:

![image](https://cloud.githubusercontent.com/assets/4248081/13513018/ef1d7524-e17c-11e5-9b68-82978bd4b15e.png)

To fix this, create a `.codeclimate.yml` file in the root of your directory and use this content:

``` yml
---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- dist/**/*
```

Notice that Code Climate not only can give you a nice code coverage report and badges, but also tell the *quality* of your code using some really neat engines and reading your ESLint configuration file.

You can also copy this file from master: [.codeclimate.yml](https://github.com/filipedeschamps/rss-feed-emitter/blob/master/.codeclimate.yml)

## Github integration

You can enable Github integrations inside **Settings > Integrations** panel of your repository. For example, you can make Code Climate analyze your code every time a Pull Request is made. Let's enable it by clicking in the **Set Up** button:

![image](https://cloud.githubusercontent.com/assets/4248081/13513253/7b1eb3ca-e17e-11e5-8740-505a9ce3ca16.png)

Code Climate will ask for a **Github personal OAuth token**:

![image](https://cloud.githubusercontent.com/assets/4248081/13513388/4f6b6952-e17f-11e5-918c-f5d63f820166.png)

They are very easy to generate, just access the [Personal Access Tokens](https://github.com/settings/tokens) in Github:

![image](https://cloud.githubusercontent.com/assets/4248081/13513436/a7c12e20-e17f-11e5-948d-92d5d9a08a13.png)

Click in **Generate new token** button and from the options, create a name for this token in **Token description** field and for **Select scopes** choose only `repo:status` and `public_repo`:

![image](https://cloud.githubusercontent.com/assets/4248081/13513470/d7186936-e17f-11e5-973b-a941af25ac3b.png)

In the bottom of that page, click **Generate token** and Github will only show you the token **one time**, please copy it to your clipboard:

![image](https://cloud.githubusercontent.com/assets/4248081/13513533/3afdf920-e180-11e5-93f3-c1d7fd506410.png)

Go back to Code Climate and paste it to the **OAuth Token** field and also enable **Update status?**, since we want Code Climate to change the Pull Request status if it finds something wrong with it:

![image](https://cloud.githubusercontent.com/assets/4248081/13513510/200c920c-e180-11e5-9df5-8782903c4618.png)

After saving this configuration, a new button **Test Service** will appear:

![image](https://cloud.githubusercontent.com/assets/4248081/13513630/259a9330-e181-11e5-8391-1db8477e04c7.png)

Click on it and it should give you an green mark:

![image](https://cloud.githubusercontent.com/assets/4248081/13513641/3f253256-e181-11e5-808d-013b9cf5a00e.png)

But there's another thing you need to configure: Github's webhook. This is necessary since Github need to notify Code Clime that there's a new Pull Request in town.

To do this, go to your Github repository, then open **Settings > Webhooks & services**

![image](https://cloud.githubusercontent.com/assets/4248081/13516008/e6970f6a-e194-11e5-879d-87a85c0a8a70.png)

Now click in the **Add webhook** button and in the follow screen, insert `https://codeclimate.com/webhooks` inside the **Payload URL** and check **Send me everything.** option.

![image](https://cloud.githubusercontent.com/assets/4248081/13515786/1c5d48dc-e193-11e5-97e1-730323642188.png)

Now click in the **Add webhook** button and this is the end result:

![image](https://cloud.githubusercontent.com/assets/4248081/13515978/a6e1c784-e194-11e5-9f37-c7ce8b12e792.png)

## Sending coverage reports to Code Climate

You need to understand that Code Climate will not automatically generate coverage reports. Some tool will generate those files and then send them to Code Climate.

Remember [we are using Istanbul](https://github.com/filipedeschamps/rss-feed-emitter/issues/131) to create our coverage reports, right? It will also generate a `coverage/lcov.info` file and some how we need to send this to Code Climate right after we run our automated tests.

We are going to use Travis to not only automatically run our tests, but also send the coverage results to Code Climate.

Before we go, we need to copy a token from Code Climate that we are going to use inside Travis. To grab this token, go to **Settings > Test Coverage > JavaScript** and find something like this:

```
CODECLIMATE_REPO_TOKEN=b84c2a82c59ba9f77fbd81c7b78b024a38bf6d5e3527dc4f819e1e1f1410e0b7 codeclimate-test-reporter < lcov.info
```

The token we are looking for is this `b84c2a82c59ba9f77fbd81c7b78b024a38bf6d5e3527dc4f819e1e1f1410e0b7`.

**Warning**: don't follow their instructions, otherwise you will expose that token to everyone. I will teach your a safer way to integrate them.

## Next step
[13. Configure Travis CI for automated tests](https://github.com/filipedeschamps/rss-feed-emitter/issues/133)

**Comment by netzulo** [comment]
maybe a gist with this comment ? @filipedeschamps , @joakimbeng , @ga2mer , @gkal19
