### ISSUE TITLE
[Question] Persistence layer

### ISSUE THREAD

**Issue by zzarcon** [filipedeschamps/rss-feed-emitter#144]
Hi, thanks for the module! I was wondering if the module gives you any way to persist the data. Like let's see I suscribe to 10 feeds and later I want to store that info somewhere in order to read it later in a different session...

If is not implemented yet but you have plans for it I will like to help ^^

**Comment by filipedeschamps** [comment]
Hi @zzarcon great! :+1: 

Currently, there's no way to persist the feed list, but I think this might be out of this module's scope, or am I wrong?

But anyway, how would you consider this feature?

Thanks!

**Comment by zzarcon** [comment]
I was just thinking on the simplest solution. Storing it in a file, maybe something like `.feed_config`, that will have some serialized `json` and later on the module can read and save new items...

But yeah probably you are right and doesn't make too much sense to implement it here, since the solution could be quite easy and the final user can easily implement it ^^. Feel free to close it if you think does not fit with the module scope!

**Comment by filipedeschamps** [comment]
Great, thanks for your input :+1:
