### ISSUE TITLE
[discussion] Add minification to dist file

### ISSUE THREAD

**Issue by matheusml** [filipedeschamps/rss-feed-emitter#145]
Inside the dist folder there's only one file (rss-feed-emitter.js) which is not minified.
What about leaving this file there, and creating another one: ```rss-feed-emitter.min.js``` which is in fact minified?

**Comment by filipedeschamps** [comment]
Hi @matheusml great! But I'm wondering, since this is a Node.js only module, does it make sense to have a minified version?

Would be nice if the module is both Node.js and Browser compatible.
