### ISSUE TITLE
Traffic wise

### ISSUE THREAD

**Issue by GreenLunar** [filipedeschamps/rss-feed-emitter#149]
According to @Martii of OUJS at https://github.com/OpenUserJs/OpenUserJS.org/issues/914#issuecomment-201225766

> A newer RSS feeds aggregator at https://github.com/filipedeschamps/rss-feed-emitter ... tested okay with Atom even though it's not mentioned anywhere but the keywords. hmmm. No limits though... that could get a little noisy (traffic wise).

**Comment by filipedeschamps** [comment]
I'm closing this issue now, but PR as always are very very very welcome 👍
