### ISSUE TITLE
Fired 'new-item' if 'title' has changed

### ISSUE THREAD

**Issue by ga2mer** [filipedeschamps/rss-feed-emitter#154]
If title has changed, 'new-item' fired.

Why not use 'guid' in RSS or 'id' in Atom if exists?

Like:
```js
return _.find( feed.items, item.guid || item.id ? {
      [ item.guid ? 'guid' : 'id' ]: item.guid || item.id
    } : {
      link: item.link,
      title: item.title
    } );
```

**Comment by filipedeschamps** [comment]
@ga2mer awesome!

The logic seems fuzzy, would you mind to make a PR implementing it with a more stepped logic?
