### ISSUE TITLE
Add text/html content type

### ISSUE THREAD

**Issue by edwinofsakh** [filipedeschamps/rss-feed-emitter#160]
I found that some RSS feeds return content type ``text/html`` even if user-agent is not browser-like.
Is it possible to add ``text/html`` to accepted content types or add the option for this?

**Comment by TobiTenno** [comment]
it's possible... could you give some use-cases where this occurs?

**Comment by TobiTenno** [comment]
If you could send me a page that does this so I can add an integration test for it, that'd be fantastic...

Even better, if you submit a pr that has a site it doesn't support because the site uses `text/html`, that'd be perfect so we specifically have something to fix

**Comment by TobiTenno** [comment]
@edwinofsakh hi, do you have a url you can provide that uses text/html so i can add it to our suite?
