### ISSUE TITLE
We need to get back to 100% coverage

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/rss-feed-emitter#162]
Hey @ga2mer I've merged your PR, sorry for the huge delay 👍 

Now it's time to get back to 100% coverage. Do you know how to write unit tests to coverage your implementation?

Bets regards.

**Comment by TobiTenno** [comment]
we're very close now, the struggle is on a line I can't figure out why it's not covered by our existing.

**Comment by TobiTenno** [comment]
we're back to it! updating our docs to have the badge from coveralls instead of code climate

**Comment by filipedeschamps** [comment]
Amazing job @TobiTenno 👏 👏 👏 👏
