### ISSUE TITLE
Specify the event name which Event emitter calls when adding a feed

### ISSUE THREAD

**Issue by re-fort** [filipedeschamps/rss-feed-emitter#163]
Thanks for the handy library!

This is a feature request.
When adding multiple feeds...
```js
feeder.add({
    url: url1,
    refresh: 6000,
})

feeder.add({
    url: url2,
    refresh: 6000,
})

feeder.on('new-item', function(item) {
    if (item.url.includes(url1)) methodA()
    else if (item.url.includes(url2)) methodB()
}
```
It's a bit troublesome when we want to handle for each feed.

```js
feeder.add({
    url: url1,
    refresh: 6000,
    eventName: 'new-item-url1',
})

feeder.add({
    url: url2,
    refresh: 6000,
    eventName: 'new-item-url2',
})

feeder.on('new-item-url1', function(item) {
}

feeder.on('new-item-url2', function(item) {
}
```
This is more simple.

Would you implement this feature?
Thanks!

**Comment by filipedeschamps** [comment]
I think what you can do for now is to create different instances, por example:

``` js
let RssFeedEmitter = require('rss-feed-emitter');
let feederUrl1 = new RssFeedEmitter();
let feederUrl2 = new RssFeedEmitter();
```

Then add and watch them separate.

What do you think?

**Comment by re-fort** [comment]
Yes, I'm doing that way for now.
If RssFeedEmitter allows to add only one feed, your suggestion is good, but thankfully it is not so. 
IMO, specifying the event name would be better than creating another instance.

**Comment by filipedeschamps** [comment]
It still seems awkward but you have a good point :)
