### ISSUE TITLE
Distribute ES6 too?

### ISSUE THREAD

**Issue by zeitiger** [filipedeschamps/rss-feed-emitter#164]
Node 8 and 9 should work with your ES6 too, so why not publish this version too aside to ES5 version?

**Comment by TobiTenno** [comment]
i'm uplifting everything in #179, trying to bring it up to some semblence of modern spec, but i don't think @filipedeschamps is maintaining this at all anymore...

**Comment by TobiTenno** [comment]
hey, this is implemented and is the primary one distributed now, @zeitiger
