### ISSUE TITLE
unable to parse urls with parameters.

### ISSUE THREAD

**Issue by sridharjsharma** [filipedeschamps/rss-feed-emitter#165]
Hi @filipedeschamps ,
I'm a newbie with rss/xml parsers.... I'm trying to parse the rss feed, but getting error as below, request your help on where am I going wrong...

**ERROR:**
```
..\node_modules\rss-feed-emitter\dist\rss-feed-emitter.js:224
        throw {
        ^
[object Object]
```

**CODE:**

```
var RssFeedEmitter =  require('rss-feed-emitter');
var feeder = new RssFeedEmitter();
var feedUrl = 'http://articlefeeds.nasdaq.com/nasdaq/categories?category=Stocks';

feeder.add({ feedUrl, refresh: 10000 });

feeder.on('new-item', function (item) {
    console.log(item);
});
feeder.list();
```

Thanks a lot,
sjs

**Comment by filipedeschamps** [comment]
I would love to fix this, and I got a challenge for you :) which is `write an integration (e2e) test to prove this broken behavior`.

You can use the PR https://github.com/filipedeschamps/rss-feed-emitter/pull/168 as benchmark.

Remember, your tests should break 👍

**Comment by sridharjsharma** [comment]
Caught the Issue, it was somewhere in long my callback sequence... Closing it...

**Comment by sridharjsharma** [comment]
Surely I need to write some UTs for my full package...
But caught the Issue in my code! it was somewhere in long my callback sequence...
