### ISSUE TITLE
Event for once the initial load is completed

### ISSUE THREAD

**Issue by MichaelPriebe** [filipedeschamps/rss-feed-emitter#170]
It would be helpful to have an event once the initial load of all the rss feeds are completed. For example, some people might not want to do anything with the items already existing in the feeds, and could do something like this:

```
feeder.on('initial-load', function () {
    console.log('Waiting for something new!')
    feeder.on('new-item', function (item) {
        doSomething(item)
    })
})
```

**Comment by MichaelPriebe** [comment]
Is this project abandoned other than security fixes?

**Comment by filipedeschamps** [comment]
@MichaelPriebe technically it's not abandoned :) I'm rearranging my work/life balance to get back to my personal projects 👍 

Once I'm back, probably this is the first feature I'm going to implement. The interface probably is going to be different than you suggested. What if you could instantiate the emitter with an option to ignore the first load?

For example:

```js
let feeder = new RssFeedEmitter({ skipFirstLoad: true })
```

**Comment by MichaelPriebe** [comment]
It would work for my case, but some people still might want the initial items, but need to know WHEN it switches from initial items to new items.

**Comment by Vezqi** [comment]
Can we get an update on this? I'd love to use this package without the initial response. :)

**Comment by dbadmin** [comment]
My temporary solution that I am using, because I am sending APNS based on this. 
let firstRun = true
feeder.on('new-item', function(item) {
   if (firstRun == true) {
       firstRun = false
   } else {
        newRSS.alert = {"title" : item.title, "subtitle" : item.pubdate, "body": item.description};
        newRSS.payload = {"New": item.description};
        newRSS.topic = "app-ID";
        apnProvider.send(newRSS, deviceToken).then( (result) => {
            console.log(result)
        });
  }

**Comment by TobiTenno** [comment]
hey @Vezqi, i'm working on adding both the case and the event keyed like... `initial-load:${feed.url}` with #184
