### ISSUE TITLE
how can i make it to show only today feeds, than old feeds?

### ISSUE THREAD

**Issue by Winthan** [filipedeschamps/rss-feed-emitter#171]
right now, all the feeds are showing, I don't wanna pull feeds from old date. is there any syntax to show current feeds.

**Comment by Sumaris** [comment]
A workaround is pulling all feeds as usual, but only showing feeds whose date corresponds with the current date. Although an option for only showing recent feeds would be better.

**Comment by Winthan** [comment]
Well pulling all feeds gonna take about hrs because I have about 200 RSS, which is more than 7000 feeds around on it. It will be good to set the date if the feed is over the time specified. Let's say, show me the feeds which are gonna be next 1 hrs from now.  Coz I want to read news feeds.

**Comment by Triniayo** [comment]
I need this too actually. Were you successful yet?

**Comment by filipedeschamps** [comment]
Related: https://github.com/filipedeschamps/rss-feed-emitter/issues/170
