### ISSUE TITLE
Support to charset encoding

### ISSUE THREAD

**Issue by pedrohh** [filipedeschamps/rss-feed-emitter#172]
Can you add support to charset encoding? In the feedparser github (https://github.com/danmactough/node-feedparser/issues/96) they added a fix to support utf8 charset. 

I'm getting this when parsing some feeds: "A�gios GPS: Esecret�rio corrup��o"

Thanks and great work!

@filipedeschamps

**Comment by TobiTenno** [comment]
from what i'm seeing, it attempts to auto-resolve it. are you looking for a way to manually provide your own?
