### ISSUE TITLE
Option to only emit new

### ISSUE THREAD

**Issue by TobiTenno** [filipedeschamps/rss-feed-emitter#175]
An option for only emitting events that occur after the emitter finishes starting would help reduce some startup thrashing for people that don't want to store ids.

**Comment by chelog** [comment]
It's pretty easy to do like so:
```js
const timeStartup = Date.now()
feed.on('message', data => {

	var time = Date.parse(data.snippet.publishedAt)
	if (time > timeStartup) {
        // post it
	}

})
```

**Comment by TobiTenno** [comment]
I already do that, it would simply be a nice option.

**Comment by TobiTenno** [comment]
other issues are bigger problems, i'll close this
