### ISSUE TITLE
What Do You Mean By "Change The User Agent"?

### ISSUE THREAD

**Issue by JimLynchCodes** [filipedeschamps/rss-feed-emitter#189]
Hi, in the README here there is a a section for user agent:

> 
> Changing the user agent for requests
> const feeder = new RssFeedEmitter({ userAgent: 'Your UA string' });
>

But I'm not sure what this means. When would someone want to set the userAgent differently? Why is this a good setting to have? It would be great if there was some text here explaining this a bit! 👍

**Comment by TobiTenno** [comment]
Some feeds and sites will filter & rate limit your requests (and time them out if they're too close together) based on several factors, one of them being your UserAgent string. In a web context, it's what distinguishes your client from other clients, and in this case it's to distinguish your feed fetcher from all others.
