### ISSUE TITLE
"skipFirstLoad: true" Doesn't Work?

### ISSUE THREAD

**Issue by JimLynchCodes** [filipedeschamps/rss-feed-emitter#190]
Hi, I am using this code:

```
const RssFeedEmitter = require('rss-feed-emitter');
const feeder = new RssFeedEmitter({ skipFirstLoad: true });

feeder.add({
    url: 'http://www.nintendolife.com/feeds/news',
    refresh: 2000
});


feeder.on('new-item', function (item) {
    console.log(item);
})

console.log('Feed watcher bot is listening... ')
```

but it returns a whole mountain of posts. I would think it shouldn't return anything but the console.log statement since the `skipFirstLoad: true` was passed in... 🤔

**Comment by JimLynchCodes** [comment]
using node v12.16.1 and `rss-feed-emitter` v3.1.0

**Comment by JimLynchCodes** [comment]
same result with node v11.15.0... 😢

**Comment by TobiTenno** [comment]
our unit tests seem to think it works fine

**Comment by midzer** [comment]
Can confirm this issue

**Comment by djholt** [comment]
I can confirm this also.

**Comment by mfreiwald** [comment]
https://github.com/filipedeschamps/rss-feed-emitter/blob/367cec24b50cb4933729f159217442004adb977e/src/FeedManager.js#L70

Must be changed to ` this.populateNewItemsInFeed(data, firstLoad); `
