### ISSUE TITLE
'new-item' event hope to add a Promise

### ISSUE THREAD

**Issue by callmesoul** [filipedeschamps/rss-feed-emitter#209]
'new-item' event hope to add a Promise
Scenes:
A website has many articles
I need to save the key words of the article, I don’t save the ones I already have
But now the'new-item' event is concurrent, there will be multiple duplicate keywords in the data inventory
Because when the last'new-item' event is still executing, how many other'new-item' events are already executing
hope:
'new-item' event hope to add a Promise
When the last'new-item' event resolves, execute another'new-item' event

**Comment by TobiTenno** [comment]
Not likely, as these are events, and they each fire separately, not with all items at a given time.
If you want all events when you finish, you can request the items object off of the feed when an event fires.

**Comment by callmesoul** [comment]
yes,
Later I found that in order to ensure that all articles on the website have been subscribed
You still need to traverse all of them every time you start
