### ISSUE TITLE
The `item.meta.link` is wrong

### ISSUE THREAD

**Issue by callmesoul** [filipedeschamps/rss-feed-emitter#211]
when mine rssurl:
`
http://localhost:4000/rss.xml
`
but in `http://localhost:4000/rss.xml`  the link is `https://callmesoul.cn/`

``` xml
<channel>
  <title>CallMeSoul</title>
  <link>https://callmesoul.cn/</link>
<channel>
```

result the item.meta.link  = `https://callmesoul.cn/rss.xml`

but is `http://localhost:4000/rss.xml` right

and sometime have use the rss response.header message
so add the rss response,request is best

**Comment by TobiTenno** [comment]
we don't set any of the meta data, that's all from your feed... this sounds like an issue with your feed.

If you can provide an exact example of the output of `http://localhost:4000/rss.xml`, then we can help you.
