### ISSUE TITLE
Does this library work in the browser?

### ISSUE THREAD

**Issue by LorhanSohaky** [filipedeschamps/rss-feed-emitter#225]
![image](https://user-images.githubusercontent.com/16273730/153729230-635d195b-d53d-4e08-b829-89f91c9026a4.png)

https://codesandbox.io/s/laughing-engelbart-94frt?file=/src/App.js

**Comment by TobiTenno** [comment]
Probably not. If you'd like to add a test for it running on web in a pr, I'll happily work on getting it working. I'm guessing request doesn't play nice with it.

**Comment by LorhanSohaky** [comment]
@TobiTenno, do you have any suggestions on how i could simulate it running on the web?

**Comment by TobiTenno** [comment]
Load up a webpage in a testing framework like jest or something similar. I'm not sure, I typically just do backend node work.
